version: "3.5"

services:
  influxdb:
    image: influxdb:2.5.0
    container_name: influxdb
    ports:
      - "8086:8086"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxpassword
      - DOCKER_INFLUXDB_INIT_ORG=pocket
      - DOCKER_INFLUXDB_INIT_BUCKET=mainnetRelay
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
