FROM golang:1.21-alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/github.com/pokt-foundation

COPY . /go/src/github.com/pokt-foundation/relay-meter/

WORKDIR /go/src/github.com/pokt-foundation/relay-meter
RUN CGO_ENABLED=0 GOOS=linux go build -a -o bin/collector ./cmd/collector/main.go

FROM alpine:3.16.0
WORKDIR /app
COPY --from=builder /go/src/github.com/pokt-foundation/relay-meter/bin/collector ./
CMD ["/app/collector"]
