FROM golang:1.21-alpine3.18 AS builder
RUN apk add --no-cache git
WORKDIR /go/src/github.com/pokt-foundation

COPY . /go/src/github.com/pokt-foundation/relay-meter/

WORKDIR /go/src/github.com/pokt-foundation/relay-meter
RUN CGO_ENABLED=0 GOOS=linux go build -a -o bin/collector ./cmd/collector/main.go

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /go/src/github.com/pokt-foundation/relay-meter/bin/collector ./
ENTRYPOINT ["/app/collector"]
