package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"time"

	driver "github.com/pokt-foundation/relay-meter/driver-autogenerated"
	"github.com/pokt-foundation/utils-go/environment"
	logger "github.com/sirupsen/logrus"

	"github.com/pokt-foundation/relay-meter/cmd"
	"github.com/pokt-foundation/relay-meter/collector"
	"github.com/pokt-foundation/relay-meter/db"
)

const (
	collectingIntervalSeconds = "COLLECTION_INTERVAL_SECONDS"
	reportIntervalSeconds     = "REPORT_INTERVAL_SECONDS"
	maxArchiveAgeDays         = "MAX_ARCHIVE_AGE"

	defaultCollectIntervalSeconds = 300
	defaultReportIntervalSeconds  = 30
	defaultMaxArchiveAgeDays      = 30
)

type options struct {
	collectionInterval int
	reportingInterval  int
	maxArchiveAge      time.Duration
}

func gatherOptions() options {
	return options{
		collectionInterval: int(environment.GetInt64(collectingIntervalSeconds, defaultCollectIntervalSeconds)),
		reportingInterval:  int(environment.GetInt64(reportIntervalSeconds, defaultReportIntervalSeconds)),
		maxArchiveAge:      time.Duration(environment.GetInt64(maxArchiveAgeDays, defaultMaxArchiveAgeDays)) * 24 * time.Hour,
	}
}

// TODO: need a /health endpoint
func main() {
	influxOptions := cmd.GatherInfluxOptions()
	postgresOptions := cmd.GatherPostgresOptions()

	influxClient := db.NewInfluxDBSource(influxOptions)

	connStr := fmt.Sprintf("postgres://%s:%s@%s/%s?sslmode=disable", postgresOptions.User, postgresOptions.Password, postgresOptions.Host, postgresOptions.DB)
	dbInst, err := sql.Open("postgres", connStr)
	if err != nil {
		fmt.Printf("Error setting up Postgres client: %v\n", err)
		os.Exit(1)
	}

	pgClient := db.NewPostgresClientFromDBInstance(dbInst)
	driver := driver.NewPostgresDriverFromDBInstance(dbInst)

	options := gatherOptions()

	fmt.Printf("Starting the collector...")
	log := logger.New()
	log.Formatter = &logger.JSONFormatter{}

	collector := collector.NewCollector([]collector.Source{influxClient, driver}, pgClient, options.maxArchiveAge, log)
	collector.Start(context.Background(), options.collectionInterval, options.reportingInterval)
}
