package main

import (
	"context"
	"fmt"
	"os"
	"time"

	driver "github.com/pokt-foundation/relay-meter/driver-autogenerated"
	"github.com/pokt-foundation/utils-go/environment"
	"github.com/pokt-foundation/utils-go/logger"

	"github.com/pokt-foundation/relay-meter/cmd"
	"github.com/pokt-foundation/relay-meter/collector"
	"github.com/pokt-foundation/relay-meter/db"
)

const (
	collectingIntervalSeconds = "COLLECTION_INTERVAL_SECONDS"
	reportIntervalSeconds     = "REPORT_INTERVAL_SECONDS"
	maxArchiveAgeDays         = "MAX_ARCHIVE_AGE"

	defaultCollectIntervalSeconds = 300
	defaultReportIntervalSeconds  = 30
	defaultMaxArchiveAgeDays      = 30
)

type options struct {
	collectionInterval int
	reportingInterval  int
	maxArchiveAge      time.Duration
}

func gatherOptions() options {
	return options{
		collectionInterval: int(environment.GetInt64(collectingIntervalSeconds, defaultCollectIntervalSeconds)),
		reportingInterval:  int(environment.GetInt64(reportIntervalSeconds, defaultReportIntervalSeconds)),
		maxArchiveAge:      time.Duration(environment.GetInt64(maxArchiveAgeDays, defaultMaxArchiveAgeDays)) * 24 * time.Hour,
	}
}

// TODO: add a /health endpoint
func main() {
	postgresOptions := cmd.GatherPostgresOptions()

	dbInst, cleanup, err := db.NewDBConnection(postgresOptions)
	if err != nil {
		fmt.Printf("Error setting up Postgres connection: %v\n", err)
		os.Exit(1)
	}
	defer func() {
		err := cleanup()
		if err != nil {
			fmt.Printf("Error during cleanup: %v\n", err)
		}
	}()

	pgClient := db.NewPostgresClientFromDBInstance(dbInst)
	driver := driver.NewPostgresDriverFromDBInstance(dbInst)

	options := gatherOptions()

	fmt.Printf("Starting the collector...")
	logger := logger.New()

	collector := collector.NewCollector([]collector.Source{driver}, pgClient, options.maxArchiveAge, logger)
	collector.Start(context.Background(), options.collectionInterval, options.reportingInterval)
}
