// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package postgresdriver

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db }
}

func NewPGX(conn pgx.Conn) *Queries {
	return &Queries{Conn: conn }
}

type Queries struct {
	db DBTX
	pgx.Conn
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
