// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgresdriver

import (
	"database/sql"
	"time"

	"github.com/pokt-foundation/portal-db/v2/types"
)

type DailyAppSum struct {
	ID           sql.NullInt32     `json:"id"`
	PortalAppID  types.PortalAppID `json:"portalAppID"`
	CountSuccess int64             `json:"countSuccess"`
	CountFailure int64             `json:"countFailure"`
	Time         sql.NullTime      `json:"time"`
}

type HttpSourceRelayCount struct {
	PortalAppID types.PortalAppID `json:"portalAppID"`
	Day         time.Time         `json:"day"`
	Success     int64             `json:"success"`
	Error       int64             `json:"error"`
}

type RelayCount struct {
	ID           sql.NullInt32     `json:"id"`
	Origin       string            `json:"origin"`
	PortalAppID  types.PortalAppID `json:"portalAppID"`
	Count        sql.NullInt64     `json:"count"`
	CountSuccess sql.NullInt32     `json:"countSuccess"`
	CountFailure sql.NullInt32     `json:"countFailure"`
	Time         sql.NullTime      `json:"time"`
}

type TodaysAppLatency struct {
	ID          sql.NullInt32     `json:"id"`
	PortalAppID types.PortalAppID `json:"portalAppID"`
	Time        string            `json:"time"`
	Latency     string            `json:"latency"`
}

type TodaysAppSum struct {
	ID           sql.NullInt32 `json:"id"`
	Application  string        `json:"application"`
	CountSuccess int64         `json:"countSuccess"`
	CountFailure int64         `json:"countFailure"`
}

type TodaysRelayCount struct {
	ID           sql.NullInt32     `json:"id"`
	Time         sql.NullTime      `json:"time"`
	PortalAppID  types.PortalAppID `json:"portalAppID"`
	Origin       string            `json:"origin"`
	CountSuccess sql.NullInt32     `json:"countSuccess"`
	CountFailure sql.NullInt32     `json:"countFailure"`
	Count        sql.NullInt64     `json:"count"`
}
