// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgresdriver

import (
	"database/sql"
	"time"

	"github.com/pokt-foundation/portal-db/v2/types"
)

type DailyAppSum struct {
	ID           sql.NullInt32            `json:"id"`
	Application  types.PortalAppPublicKey `json:"application"`
	CountSuccess int64                    `json:"countSuccess"`
	CountFailure int64                    `json:"countFailure"`
	Time         sql.NullTime             `json:"time"`
}

type HttpSourceRelayCount struct {
	AppPublicKey types.PortalAppPublicKey `json:"appPublicKey"`
	Day          time.Time                `json:"day"`
	Success      int64                    `json:"success"`
	Error        int64                    `json:"error"`
}

type RelayCount struct {
	ID           sql.NullInt32            `json:"id"`
	Origin       types.PortalAppOrigin    `json:"origin"`
	Application  types.PortalAppPublicKey `json:"application"`
	Count        sql.NullInt64            `json:"count"`
	CountSuccess sql.NullInt32            `json:"countSuccess"`
	CountFailure sql.NullInt32            `json:"countFailure"`
	Time         sql.NullTime             `json:"time"`
}

type TodaysAppLatency struct {
	ID          sql.NullInt32            `json:"id"`
	Application types.PortalAppPublicKey `json:"application"`
	Time        string                   `json:"time"`
	Latency     string                   `json:"latency"`
}

type TodaysAppSum struct {
	ID           sql.NullInt32            `json:"id"`
	Application  types.PortalAppPublicKey `json:"application"`
	CountSuccess int64                    `json:"countSuccess"`
	CountFailure int64                    `json:"countFailure"`
}

type TodaysRelayCount struct {
	ID           sql.NullInt32            `json:"id"`
	Time         sql.NullTime             `json:"time"`
	Application  types.PortalAppPublicKey `json:"application"`
	Origin       types.PortalAppOrigin    `json:"origin"`
	CountSuccess sql.NullInt32            `json:"countSuccess"`
	CountFailure sql.NullInt32            `json:"countFailure"`
	Count        sql.NullInt64            `json:"count"`
}
