// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package postgresdriver

import (
	"context"
	"time"
)

const insertHTTPSourceRelayCount = `-- name: InsertHTTPSourceRelayCount :exec
INSERT INTO http_source_relay_count (app_public_key, day, success, error)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_public_key, day) DO UPDATE
    SET success = http_source_relay_count.success + excluded.success,
        error = http_source_relay_count.error + excluded.error
`

type InsertHTTPSourceRelayCountParams struct {
	AppPublicKey string    `json:"appPublicKey"`
	Day          time.Time `json:"day"`
	Success      int64     `json:"success"`
	Error        int64     `json:"error"`
}

func (q *Queries) InsertHTTPSourceRelayCount(ctx context.Context, arg InsertHTTPSourceRelayCountParams) error {
	_, err := q.db.ExecContext(ctx, insertHTTPSourceRelayCount,
		arg.AppPublicKey,
		arg.Day,
		arg.Success,
		arg.Error,
	)
	return err
}

const selectHTTPSourceRelayCounts = `-- name: SelectHTTPSourceRelayCounts :many
SELECT app_public_key, day, success, error
FROM http_source_relay_count
WHERE day BETWEEN $1 AND $2
`

type SelectHTTPSourceRelayCountsParams struct {
	Day   time.Time `json:"day"`
	Day_2 time.Time `json:"day2"`
}

func (q *Queries) SelectHTTPSourceRelayCounts(ctx context.Context, arg SelectHTTPSourceRelayCountsParams) ([]HttpSourceRelayCount, error) {
	rows, err := q.db.QueryContext(ctx, selectHTTPSourceRelayCounts, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HttpSourceRelayCount
	for rows.Next() {
		var i HttpSourceRelayCount
		if err := rows.Scan(
			&i.AppPublicKey,
			&i.Day,
			&i.Success,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
