name: Lint & Test

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Golang ci Action
        uses: golangci/golangci-lint-action@v3

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Unit tests
        run: make test_unit

      - name: Run Driver tests
        run: make test_driver

      - name: Build the Docker test stack
        run: make test_env_up

      - name: Run E2E test
        run: make run_e2e_tests
