name: Production deployment us-west-2

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Relay meter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (Collector)
        id: build-image-collector
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: relay-meter-collector
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.production.collector .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Build, tag, and push image to Amazon ECR (API)
        id: build-image-api-server
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: relay-meter-server
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.production.apiserver .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID / us-west-2 - collector
        id: task-def-us-west-2-collector
        uses: aws-actions/amazon-ecs-render-task-definition@master
        with:
          task-definition: .aws/ecs-task-definition.json
          container-name: relay-meter-collector
          image: ${{ steps.build-image-collector.outputs.image }}
          environment-variables: |
            INFLUXDB_TOKEN=${{ secrets.INFLUXDB_TOKEN }}
            INFLUXDB_URL=${{ secrets.INFLUXDB_URL }}
            INFLUXDB_ORG=${{ secrets.INFLUXDB_ORG }}
            INFLUXDB_BUCKET_DAILY=${{ secrets.INFLUXDB_BUCKET_DAILY }}
            INFLUXDB_BUCKET_CURRENT=${{ secrets.INFLUXDB_BUCKET_CURRENT }}
            INFLUXDB_ORIGIN_BUCKET_DAILY=${{ secrets.INFLUXDB_ORIGIN_BUCKET_DAILY }}
            INFLUXDB_ORIGIN_BUCKET_CURRENT=${{ secrets.INFLUXDB_ORIGIN_BUCKET_CURRENT }}
            COLLECTION_INTERVAL_SECONDS=${{ secrets.COLLECTION_INTERVAL_SECONDS }}
            ENV_REPORT_INTERVAL_SECONDS=${{ secrets.ENV_REPORT_INTERVAL_SECONDS }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=5432
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            ENABLE_WRITING= ${{ secrets.ENABLE_WRITING }}
            POSTGRES_USE_PRIVATE= ${{ secrets.POSTGRES_USE_PRIVATE }}

      - name: Fill in the new image ID / us-west-2 - server
        id: task-def-us-west-2-server
        uses: aws-actions/amazon-ecs-render-task-definition@master
        with:
          task-definition: ${{ steps.task-def-us-west-2-collector.outputs.task-definition }}
          container-name: relay-meter-server
          image: ${{ steps.build-image-api-server.outputs.image }}
          environment-variables: |
            API_SERVER_PORT=80
            BACKEND_API_URL=${{ secrets.BACKEND_API_URL }}
            BACKEND_API_TOKEN=${{ secrets.PHD_API_KEY_SERVICE_PRODUCTION }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=5432
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            API_KEYS=${{ secrets.API_KEYS }}
            POSTGRES_USE_PRIVATE= ${{ secrets.POSTGRES_USE_PRIVATE }}

      - name: Deploy / us-west-2
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-us-west-2-server.outputs.task-definition }}
          service: relay-meter
          cluster: relay-meter
          wait-for-service-stability: true
