name: Tag and release
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build & Test"]
    branches: [main]
    types:
      - completed

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.POKT_BOT_GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          release_body: ":rocket: Release Notes !:fireworks: "
          use_github_release_notes: true
